### ISSUE TITLE
The Source of data.pkl?

### ISSUE THREAD

**Issue by HainoMajou** [ICDM-UESTC/MMRA#1]
I'm wondering the source of data.pkl
Or is there any preprocessing part for the source dataset (videos, images, csvs) to transform into data.pkl?

**Comment by Jian-Lang** [comment]
Fine! I will later upload the process of data preprocessing.

**Comment by JackLo111** [comment]
So lucky someone else has found the same mistake, but the author seems not to update the bug utill now

**Comment by Jian-Lang** [comment]
Hi, sorry for late uploading. I have uploaded the Data.md which can help u to reproduce the data.pkl and other data files.
