### ISSUE TITLE
Where is the  'data.pkl'

### ISSUE THREAD

**Issue by JackLo111** [ICDM-UESTC/MMRA#2]
I thoroughly searched the whole packege, I can't find the source of the  'data.pkl' in file 'dataset_split.py'. Could you please tell me how to produce the data.pkl or what is actually in you data.pkl?

**Comment by Jian-Lang** [comment]
Fine, Thanks for ur asking. I will later upload the whole process of data preprocessing!

**Comment by Jian-Lang** [comment]
I have uploaded the Data.md which can help u to reproduce the data.pkl and other data files.
