### ISSUE TITLE
visual_engineering

### ISSUE THREAD

**Issue by chensh911** [ICDM-UESTC/MMRA#5]
In reviewing the visual_engineering.py script, I noticed that the vit_visual_feature_extraction function processes a single image frame (I'm not sure is it correct?).
So how to handle multiple frames from a video (like averaging the features or another approach), or is this functionality handled in your code elsewhere?
( I think provide executable code for data preprocess will make it more convenient to reproduce if possible.)

**Comment by Jian-Lang** [comment]
Thanks for your attention to our work. To handle multiple frames, we concatenate the features of each frame to form a video feature with the number of frames multiplied by the feature dimension. 
Hope it helps you!

**Comment by chensh911** [comment]
Many thanks for your response.
